# Site settings
title: Emacs Customize 101
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  これはEmacsカスタマイズの為の情報をまとめるブログもどきです。
baseurl: "/emacs-customize-101-jp" # the subpath of your site, e.g. /blog/
url: "http://rizaudo.github.com/emacs-customize-101-jp" # the base hostname & protocol for your site
twitter_username: rizaudo
github_username:  rizaudo

# Build settings
markdown: kramdown
