#+TITLE: カスタマイズに使えるパッケージ
#+DATE: 2015-03-28
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: package
#+JEKYLL_PUBLISHED: true
#+STARTUP: indent

# 結構大きくなった紹介とかは、別ページに飛ばすようにします。
* TL;DR
パッケージについて紹介していますが、めんどくさかったらquickstartを見
てスターターキットを入れましょう。大体の設定はしてくれますし、それ以
上の挙動はinit.elに追記すれば良いだけになります。

* 推奨パッケージ
Emacsは環境であると言われるように、Emacsでは使うパッケージによっ
て使い勝手に差が出ます。 この記事ではEmacsで使うと良いであろうパッ
ケージについて紹介します。特に何も書いてない場合、MELPAからインストールできると思います。
** Better Defaults
一部の人にはおなじみのtechnomancy[fn::https://github.com/technomancy]
という方が作っている、Emacsのデフォルトを少し改善するパッケージです。
内容としてはido, uniquify, saveplaceに対してのちょっとした設定、括弧の
対応の有効化、Menu-barなどの無効化が入っています。導入方法は以下の通りで
す
#+BEGIN_SRC emacs-lisp
M-x package-install better-defaults
#+END_SRC

** Starter-kit
Better Defaultsと同じ作者によるパッケージ、及びガイドです。推奨してお
きながら何ですが、パッケージ版がかなり古いため、試しに使ってみて、設定
を参考にするのに良いかと思って紹介しました。ガイドのほうは中々良いパッケー
ジをオススメして、一見の価値がありますので、是非参考にどうぞ。導入方法は
以下の通りです。
#+BEGIN_SRC emacs-lisp
M-x package-install starter-kit
#+END_SRC

** ido
Ido(Interactively do)とはバッファやファイルやディレクトリなどを
選択する動作を、単語で絞り込んでいくように変更するEmacsのデフォルトパッケージ
です。\keys{C-s}と\keys{C-r}でカーソルの前後の移動で、
\keys{RET}で選択の決定です。
日本ではAnything/Helmが人気だと思われますが、海外のEmacsに関
する情報を見る限り、海外ではIdoの方が人気であるようです。
恐らくhelm/anythingを使わないというなら、まず使う事になると思われます。

#+BEGIN_SRC emacs-lisp
(require 'ido)
(setq ido-enable-flex-matching t)
#+END_SRC

** Smex
Emacs使い初めだとまずコマンド覚えてないので標準のM-xは使いにくいです。
SmexはM-xをido-modeのようにするパッケージで、helm/anythingを使わないな
らまず使うと良いパッケージです。

** helm/anything
[書く予定ですが、筆者は良く知らないので難航しています]

** Web Browser
*** eww(Emacs Web Wowser)
現在のEmacsは標準でウェブブラウザを持っています。
GUI版Emacsを使っている場合は画像を表示できます。プログラミング中な
どにブラウザが横に表示されているというのは大変便利であるため、簡単な使い方
を書きたいと思います。
起動は以下のコマンドです。
#+BEGIN_SRC emacs-lisp
M-x eww
#+END_SRC
#+ATTR_LATEX: :environment tabular :align l|l
| キーバインド | 機能                               |
|--------------+------------------------------------|
| DEL          | 上にスクロール                     |
| SPC          | 下にスクロール                     |
| &            | 外部のブラウザで現在のページを開く |
| H            | 履歴                               |
| d            | ダウンロード                       |
| b            | ブックマークに追加                 |
| v            | 開いているページのソースを表示     |
| w            | 開いているページのURLをコピー      |
| q            | ewwを終了                          |
*** w3m
w3m[fn::同名なのでわかりにくいですが、パッケージ名です]はテキストブラウザとして有名なw3mをEmacsから使えるようにしたパッケージで
す。
ewwが出てくるまではEmacsでのブラウザというとこれくらいしかありませんで
した。注意点として、w3mが無いと動かないため、Windowsで使
おうとすると面倒な事になります。上述のewwはデフォルトでEmacsに入っているため、特別な
理由が無ければewwを使うと良いのではないでしょうか。
** 自動補完
*** Autocomplete
良く知られている、自動補完パッケージです。
そのうち書くので、今はこの辺りを読んでみてください
([[http://cx4a.org/software/auto-complete/manual.ja.html][日本語マニュアル]])。

*** Company
Autocompleteと同じような自動補完パッケージです。
Autocompleteよりも昔からあったので、古いパッケージではCompanyし
か対応していないものもあります

