#+TITLE: misc
#+DATE: 2014-12-31
#+JEKYLL_CATEGORIES: misc
#+SETUPFILE: ../setupfile.org
#+OPTIONS: toc:t

この辺りはよく解らないパッケージ情報を載せています。
特に書いてなければEmacs標準のパッケージです。

* 有用？
*** food-dice(marmaladeパッケージ)
飯を決めるのがめんどくさい人に。サイコロ飯が出来ます。
候補を入れるだけで、何か適当に出してくれます。
#+BEGIN_SRC
(setq fooddice/meals '(pizza pommes burger noodles bread soup chinese sushi))
(setq fooddice/drinks '(cola water coffee tea beer whisky milk cacao icetea energydrink))
(setq fooddice/restaurants '(italian chinese thai american japanese))
#+END_SRC
#+BEGIN_SRC
M-x what-to-eat
M-x where-to-eat
M-x what-to-drink
#+END_SRC
*** decipher
暗号解読のお供に。
*** dissociated-press
四散新聞というテキストを入れて別のテキストを得るアルゴリズムを実装したコマンドです。
* ゲーム
*** tetris
テトリスです。説明が必要ないでしょう。
#+BEGIN_SRC
M-x tetris
#+END_SRC
*** mpuz
覆面算が好きですか？
#+BEGIN_SRC
M-x mpuz
#+END_SRC
*** blackbox
ブラックボックスの外側からX線を発射して、中にある玉の場所を当てるゲームです。
SPCでX線の発射か玉のフラグを立てる事が出来ます。
簡単な記号の説明
 - [数字] 発射したX線が同じ数字の所から出た
 - [H] 玉にX線が当たった
 - [R] 発射した所にX線が戻って来た
#+BEGIN_SRC
M-x blackbox
#+END_SRC
*** snake
色んなサンプルゲームとかでおなじみのスネークゲーム。
#+BEGIN_SRC
M-x snake
#+END_SRC
*** Dunnet
昔のテキストアドベンチャーゲーム。
コマンドを自分で打って探して進めて行くタイプのです。
暇つぶしと英単語力を試すのに良いかも。
#+BEGIN_SRC
M-x dunnet
#+END_SRC
*** gomoku
五目並べ。とても強いです。
罵ってくるので余裕のある時に。
#+BEGIN_SRC
M-x gomoku
#+END_SRC
*** honoi
ハノイの塔です。
C-u で欲しい数を渡せます。
#+BEGIN_SRC
M-x hanoi
#+END_SRC
*** bubbles
どれだけ少ない回数でバブルを消せるかというゲームです。
やってみると大体わかります。
*** life
お馴染みライフゲームです。
*** landmark
???
*** morse-region
モールス信号に変更してくれます。
以下で複合化です。
#+BEGIN_SRC emacs-lisp
M-x unmorse-region
#+END_SRC
*** pong
これ一人で出来ない...
*** zone
Emacsをidle状態にしているときに使うと良いですね。
*** animate
文字をアニメーションするためのパッケージです。
*** 5x5
ライツアウトというゲームの逆版です。全てを白で埋めたら勝ち。
